language: php

matrix:
    include:
        - php: 5.3
          env: deps=low
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
    fast_finish: true
    
install:
  - sudo apt-get install nginx
  - if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf; fi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f .travis_nginx.conf /etc/nginx/sites-enabled/default.conf
  - sudo sed -e "s?%APP_DIR%?$(pwd)/features/application?g" --in-place /etc/nginx/sites-enabled/default.conf
  - sudo service nginx restart

before_script:
  - phpenv config-rm xdebug.ini
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer install; fi

script:
  - ./bin/phpspec run -f pretty
  - ./bin/behat --profile=ci --format=progress

